server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: ""
    sql-migration-separator: "_"
    sql-migration-suffixes: .sql
    out-of-order: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

clients:
  catalog-service:
    url: http://localhost:8081
  user-service:
    url: http://localhost:8083


security:
  jwt:
    secret: "very-secret-key-very-secret-key-1234567890"
